/* ---------- Builtins curated for Obsidian ---------- */

// Markdown basics (kept from earlier, moved into catalog)
export const BUILTIN_MARKDOWN_YAML = `matches:
  - trigger: ":todo"
    replace: "- [ ] CURSOR_PLACEHOLDER"
  - trigger: ":quote"
    replace: "> CURSOR_PLACEHOLDER"
  - trigger: ":bold"
    replace: "**CURSOR_PLACEHOLDER**"
  - trigger: ":italic"
    replace: "_CURSOR_PLACEHOLDER_"
  - trigger: ":strike"
    replace: "~~CURSOR_PLACEHOLDER~~"
  - trigger: ":h1"
    replace: "# CURSOR_PLACEHOLDER"
  - trigger: ":h2"
    replace: "## CURSOR_PLACEHOLDER"
  - trigger: ":h3"
    replace: "### CURSOR_PLACEHOLDER"
  - trigger: ":h4"
    replace: "#### CURSOR_PLACEHOLDER"
  - trigger: ":ul"
    replace: "- CURSOR_PLACEHOLDER"
  - trigger: ":ol"
    replace: "1. CURSOR_PLACEHOLDER"
  - trigger: ":check"
    replace: "- [x] CURSOR_PLACEHOLDER"
  - trigger: ":link"
    replace: "[CURSOR_PLACEHOLDER](url)"
  - trigger: ":image"
    replace: "![CURSOR_PLACEHOLDER](url)"
  - trigger: ":wikilink"
    replace: "[[CURSOR_PLACEHOLDER]]"
  - trigger: ":alias"
    replace: "[[note|CURSOR_PLACEHOLDER]]"
  - trigger: ":hr"
    replace: "---"
`;

// Obsidian callouts
export const BUILTIN_CALLOUTS_YAML = `matches:
  # Базовые
  - trigger: ":note"
    replace: "> [!note] CURSOR_PLACEHOLDER\\n> "
  - trigger: ":tip"
    replace: "> [!tip] CURSOR_PLACEHOLDER\\n> "
  - trigger: ":info"
    replace: "> [!info] CURSOR_PLACEHOLDER\\n> "
  - trigger: ":warn"
    replace: "> [!warning] CURSOR_PLACEHOLDER\\n> "
  - trigger: ":danger"
    replace: "> [!danger] CURSOR_PLACEHOLDER\\n> "
  - trigger: ":quote-callout"
    replace: "> [!quote]\\n> CURSOR_PLACEHOLDER"
  - trigger: ":abstract"
    replace: "> [!abstract] CURSOR_PLACEHOLDER\\n> "
  - trigger: ":summary"
    replace: "> [!summary] CURSOR_PLACEHOLDER\\n> "
  - trigger: ":tldr"
    replace: "> [!tldr] CURSOR_PLACEHOLDER\\n> "
  - trigger: ":example"
    replace: "> [!example] CURSOR_PLACEHOLDER\\n> "
  - trigger: ":faq"
    replace: "> [!faq] CURSOR_PLACEHOLDER\\n> "
  - trigger: ":question"
    replace: "> [!question] CURSOR_PLACEHOLDER\\n> "
  - trigger: ":todo-callout"
    replace: "> [!todo] CURSOR_PLACEHOLDER\\n> - [ ] "
  - trigger: ":success"
    replace: "> [!success] CURSOR_PLACEHOLDER\\n> "
  - trigger: ":check-callout"
    replace: "> [!check] CURSOR_PLACEHOLDER\\n> "
  - trigger: ":done"
    replace: "> [!done] CURSOR_PLACEHOLDER\\n> "
  - trigger: ":failure"
    replace: "> [!failure] CURSOR_PLACEHOLDER\\n> "
  - trigger: ":missing"
    replace: "> [!missing] CURSOR_PLACEHOLDER\\n> "
  - trigger: ":error"
    replace: "> [!error] CURSOR_PLACEHOLDER\\n> "
  - trigger: ":bug"
    replace: "> [!bug] CURSOR_PLACEHOLDER\\n> "
  - trigger: ":cite"
    replace: "> [!cite] CURSOR_PLACEHOLDER\\n> "
`;

// Unicode arrows
export const BUILTIN_UNICODE_ARROWS_YAML = `matches:
  - triggers: [":rarrow", ":->"]
    replace: "→"
  - triggers: [":larrow", ":<-"]
    replace: "←"
  - trigger: ":uparrow"
    replace: "↑"
  - trigger: ":downarrow"
    replace: "↓"
  - trigger: ":dblarrow"
    replace: "↔"
`;

// Math symbols (lite)
export const BUILTIN_MATH_LITE_YAML = `matches:
  - trigger: ":pm"
    replace: "±"
  - trigger: ":times"
    replace: "×"
  - trigger: ":div"
    replace: "÷"
  - trigger: ":le"
    replace: "≤"
  - trigger: ":ge"
    replace: "≥"
  - trigger: ":neq"
    replace: "≠"
  - trigger: ":approx"
    replace: "≈"
  - trigger: ":deg"
    replace: "°"
  - trigger: ":mu"
    replace: "µ"
  - trigger: ":inf"
    replace: "∞"
`;

// Emoji (lite)
export const BUILTIN_EMOJI_LITE_YAML = `matches:
  # 😀 Смайлики — базовые
  - trigger: ":grinning"
    replace: "😀"
  - trigger: ":smiley"
    replace: "😃"
  - trigger: ":smile"
    replace: "😄"
  - trigger: ":grin"
    replace: "😁"
  - trigger: ":laughing"
    replace: "😆"
  - trigger: ":sweat_smile"
    replace: "😅"
  - trigger: ":joy"
    replace: "😂"
  - trigger: ":rofl"
    replace: "🤣"
  - trigger: ":slight_smile"
    replace: "🙂"
  - trigger: ":upside_down"
    replace: "🙃"
  - trigger: ":wink"
    replace: "😉"
  - trigger: ":blush"
    replace: "😊"
  - trigger: ":yum"
    replace: "😋"
  - trigger: ":sunglasses"      
    replace: "😎"
  - trigger: ":heart_eyes"      
    replace: "😍"
  - trigger: ":kissing_heart"   
    replace: "😘"
  - trigger: ":kissing"         
    replace: "😗"
  - trigger: ":relaxed"         
    replace: "☺️"
  - trigger: ":kissing_smiling" 
    replace: "😙"
  - trigger: ":kissing_closed"  
    replace: "😚"
  - trigger: ":hug"             
    replace: "🤗"
  - trigger: ":star_struck"     
    replace: "🤩"
  - trigger: ":thinking"        
    replace: "🤔"
  - trigger: ":zipper_mouth"    
    replace: "🤐"
  - trigger: ":neutral"         
    replace: "😐"
  - trigger: ":expressionless"  
    replace: "😑"
  - trigger: ":no_mouth"        
    replace: "😶"
  - trigger: ":smirk"           
    replace: "😏"
  - trigger: ":unamused"        
    replace: "😒"
  - trigger: ":roll_eyes"       
    replace: "🙄"
  - trigger: ":grimacing"       
    replace: "😬"
  - trigger: ":lying"           
    replace: "🤥"
  - trigger: ":relieved"        
    replace: "😌"
  - trigger: ":pensive"         
    replace: "😔"
  - trigger: ":sleepy"          
    replace: "😪"
  - trigger: ":sleeping"        
    replace: "😴"
  - trigger: ":drooling"        
    replace: "🤤"
  - trigger: ":mask"            
    replace: "😷"
  - trigger: ":facepalm"        
    replace: "🤦"
  - trigger: ":shrug_emoji"     
    replace: "🤷"
  - trigger: ":mind_blown"      
    replace: "🤯"

  # 😢 Негатив/эмоции
  - trigger: ":confused"        
    replace: "😕"
  - trigger: ":worried"         
    replace: "😟"
  - trigger: ":slight_frown"    
    replace: "🙁"
  - trigger: ":frowning"        
    replace: "☹️"
  - trigger: ":open_mouth"      
    replace: "😮"
  - trigger: ":hushed"          
    replace: "😯"
  - trigger: ":astonished"      
    replace: "😲"
  - trigger: ":flushed"         
    replace: "😳"
  - trigger: ":pleading"        
    replace: "🥺"
  - trigger: ":cry"             
    replace: "😢"
  - trigger: ":sob"             
    replace: "😭"
  - trigger: ":persevere"       
    replace: "😣"
  - trigger: ":disappointed"    
    replace: "😞"
  - trigger: ":downcast"        
    replace: "😓"
  - trigger: ":cold_sweat"      
    replace: "😰"
  - trigger: ":weary"           
    replace: "😩"
  - trigger: ":tired"           
    replace: "😫"
  - trigger: ":angry"           
    replace: "😠"
  - trigger: ":pout"            
    replace: "😡"
  - trigger: ":exploding"       
    replace: "🤯"
  - trigger: ":skull"           
    replace: "💀"
  - trigger: ":clown"           
    replace: "🤡"

  - trigger: ":thumbsup"        
    replace: "👍"
  - trigger: ":thumbsdown"      
    replace: "👎"
  - trigger: ":ok_hand"         
    replace: "👌"
  - trigger: ":pinched"         
    replace: "🤌"
  - trigger: ":pinch"           
    replace: "🤏"
  - trigger: ":v"               
    replace: "✌️"
  - trigger: ":crossed_fingers" 
    replace: "🤞"
  - trigger: ":handshake"       
    replace: "🤝"
  - trigger: ":clap"            
    replace: "👏"
  - trigger: ":pray"            
    replace: "🙏"
  - trigger: ":wave"            
    replace: "👋"
  - trigger: ":raised_hand"     
    replace: "✋"
  - trigger: ":muscle"          
    replace: "💪"
  - trigger: ":point_up"        
    replace: "☝️"
  - trigger: ":point_right"     
    replace: "👉"
  - trigger: ":point_left"      
    replace: "👈"
  - trigger: ":point_down"      
    replace: "👇"

  - trigger: ":heart"           
    replace: "❤️"
  - trigger: ":orange_heart"    
    replace: "🧡"
  - trigger: ":yellow_heart"    
    replace: "💛"
  - trigger: ":green_heart"     
    replace: "💚"
  - trigger: ":blue_heart"      
    replace: "💙"
  - trigger: ":purple_heart"    
    replace: "💜"
  - trigger: ":black_heart"     
    replace: "🖤"
  - trigger: ":white_heart"     
    replace: "🤍"
  - trigger: ":brown_heart"     
    replace: "🤎"
  - trigger: ":sparkling_heart" 
    replace: "💖"
  - trigger: ":two_hearts"      
    replace: "💕"
  - trigger: ":heartbeat"       
    replace: "💓"
  - trigger: ":broken_heart"    
    replace: "💔"
  - trigger: ":revolving_hearts"
    replace: "💞"

  - trigger: ":sparkles"        
    replace: "✨"
  - trigger: ":star"            
    replace: "⭐️"
  - trigger: ":boom"            
    replace: "💥"
  - trigger: ":fire"            
    replace: "🔥"
  - trigger: ":100"             
    replace: "💯"
  - trigger: ":tada"            
    replace: "🎉"
  - trigger: ":balloon"         
    replace: "🎈"
  - trigger: ":confetti"        
    replace: "🎊"
  - trigger: ":check"           
    replace: "✔️"
  - trigger: ":heavy_check"     
    replace: "✅"
  - trigger: ":x"               
    replace: "❌"
  - trigger: ":warning"         
    replace: "⚠️"
  - trigger: ":info_symbol"     
    replace: "ℹ️"
  - trigger: ":question"        
    replace: "❓"
  - trigger: ":grey_question"   
    replace: "❔"
  - trigger: ":exclamation"     
    replace: "❗️"
  - trigger: ":double_excl"     
    replace: "‼️"
  - trigger: ":atm"             
    replace: "💳"
  - trigger: ":moneybag"        
    replace: "💰"
  - trigger: ":chart_up"        
    replace: "📈"
  - trigger: ":chart_down"      
    replace: "📉"
  - trigger: ":paperclip"       
    replace: "📎"
  - trigger: ":pushpin"         
    replace: "📌"
  - trigger: ":link"            
    replace: "🔗"
  - trigger: ":lock"            
    replace: "🔒"
  - trigger: ":unlock"          
    replace: "🔓"
  - trigger: ":hourglass"       
    replace: "⌛️"
  - trigger: ":alarm"           
    replace: "⏰"
  - trigger: ":calendar"        
    replace: "📅"
  - trigger: ":memo"            
    replace: "📝"
  - trigger: ":bookmark"        
    replace: "🔖"
  - trigger: ":mag"             
    replace: "🔍"
  - trigger: ":bulb"            
    replace: "💡"
  - trigger: ":hammer"          
    replace: "🔨"
  - trigger: ":wrench"          
    replace: "🔧"
  - trigger: ":gear"            
    replace: "⚙️"

  - trigger: ":coffee"          
    replace: "☕️"
  - trigger: ":tea"             
    replace: "🫖"
  - trigger: ":beer"            
    replace: "🍺"
  - trigger: ":cheers"          
    replace: "🍻"
  - trigger: ":wine"            
    replace: "🍷"
  - trigger: ":cocktail"        
    replace: "🍸"
  - trigger: ":pizza"           
    replace: "🍕"
  - trigger: ":burger"          
    replace: "🍔"
  - trigger: ":fries"           
    replace: "🍟"
  - trigger: ":cake"            
    replace: "🍰"
  - trigger: ":cookie"          
    replace: "🍪"
  - trigger: ":apple"           
    replace: "🍎"

  - trigger: ":dog"             
    replace: "🐶"
  - trigger: ":cat"             
    replace: "🐱"
  - trigger: ":fox"             
    replace: "🦊"
  - trigger: ":bear"            
    replace: "🐻"
  - trigger: ":panda"           
    replace: "🐼"
  - trigger: ":unicorn"         
    replace: "🦄"

  - trigger: ":back"            
    replace: "◀️"
  - trigger: ":next"            
    replace: "▶️"
  - trigger: ":top"             
    replace: "🔝"
  - trigger: ":soon"            
    replace: "🔜"
  - trigger: ":fast_forward"    
    replace: "⏩"
  - trigger: ":rewind"          
    replace: "⏪"
`;

// Task states (builtin)
export const BUILTIN_TASKS_YAML = `matches:
  # Базовое todo
  - trigger: ":todo"
    replace: "- [ ] CURSOR_PLACEHOLDER"

  # Выполнено
  - trigger: ":done"
    replace: "- [x] CURSOR_PLACEHOLDER"

  # В процессе
  - trigger: ":doing"
    replace: "- [/] CURSOR_PLACEHOLDER"

  # Отложено / ожидание
  - trigger: ":waiting"
    replace: "- [-] CURSOR_PLACEHOLDER"

  # Отменено
  - trigger: ":cancel"
    replace: "- [~] CURSOR_PLACEHOLDER"

  # Планируется (scheduled)
  - trigger: ":sched"
    replace: "- [?] CURSOR_PLACEHOLDER"

  # Дважды проверить
  - trigger: ":important"
    replace: "- [!] CURSOR_PLACEHOLDER"
`;
