name: ci
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npx tsc -p tsconfig.json --noEmit

      - name: Verify versions (package.json vs manifest.json)
        run: node scripts/assert-versions.cjs

      - name: Unit tests (with coverage gates)
        run: npm run test

      - name: Build release bundle
        run: npm run build

      - name: Pack plugin zip
        run: npm run release:zip

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: true
          verbose: true

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/**

      - name: Upload plugin bundle
        uses: actions/upload-artifact@v4
        with:
          name: snipsidian-bundle
          path: |
            main.js
            manifest.json
            styles.css
            snipsidian-*.zip
          if-no-files-found: error
